### ISSUE TITLE
improper truncation of min/max values 

### ISSUE THREAD

**Issue by pbellec** [brainsprite/brainsprite#74] opened 2020-04-09 03:36 UTC
brainsprite only displays a limited number of decimals for the min/max, which is expected, but it also happens to truncate "250" as "25", which is highly problematic. This happens through the nilearn API, but it is possible that the bug is in brainsprite js code.

**Comment by kchapelier** [comment] 2020-04-11 08:30
Hi,

The issue is indeed in brainsprite codebase. I'll post a PR shortly as it is fixed in my local version.

**Comment by pbellec** [comment] 2020-04-11 13:14
very much appreciated, looking forward to the PR!

**Closed** 2020-04-11 17:44 UTC
